var appStrings = {
  "Welcome back! Sign In": "Welcome back! Sign In",
  "Email or username": "Email or username",
  "Please enter your email": "Please enter your email",
  "Email": "Email",
  "Password": "Password",
  "Please enter your password": "Please enter your password",
  "Enter password": "Enter password",
  "Remember me": "Remember me",
  "Forgot Password?": "Forgot Password?",
  "Login": "Login",
  "Do not have account?": "Do not have account?",
  "Register": "Register",
  "OR": "OR",
  "Sign in with Google": "Sign in with Google",
  "Sign in with Facebook": "Sign in with Facebook",
  "Reset password": "Reset password",
  "Enter the email you used to creat account and we will send instruction for reseting password":
      "Enter the email you used to creat account and we will send instruction for reseting password",
  "Enter Email": "Enter Email",
  "Send Instructions": "Send Instructions",
  "Enter the 4 digit code": "Enter the 4 digit code",
  "Enter the 4 digit code we sent to to your email in order to reset password":
      "Enter the 4 digit code we sent to to your email in order to reset password",
  "Did not receive?": "Did not receive?",
  "Send again": "Send again",
  "New password": "New password",
  "Enter new password": "Enter new password",
  "Your new password should be different from previously used passwords":
      "Your new password should be different from previously used passwords",
  "Repeat new password": "Repeat new password",
  "Please retype your password": "Please retype your password",
  "Change password": "Change password",
  "Choose country": "Choose country",
  "City": "City",
  "Please enter your city": "Please enter your city",
  "Enter your city": "Enter your city",
  "Full name": "Full name",
  "Please enter your full name": "Please enter your full name",
  "Enter your full name": "Enter your full name",
  "Username": "Username",
  "Please enter your username": "Please enter your username",
  "Enter your username": "Enter your username",
  "Enter your email": "Enter your email",
  "Confirm Password": "Confirm Password",
  "Retype password": "Retype password",
  "Have an account?": "Have an account?",
  "Sign in": "Sign in",
  "Register to join us": "Register to join us",
  "Verify Email": "Verify Email",
  "I agree with the terms and conditions":
      "I agree with the terms and conditions",
  "Sign up": "Sign up",
  "You must agree with the terms and conditions to register":
      "You must agree with the terms and conditions to register",
  "Password did not match": "Password did not match",
  "Password must be at least 6 characters":
      "Password must be at least 6 characters",
  "Already have an account?": "Already have an account?",
  "All donators": "All donators",
  "Goal": "Goal",
  "Raised": "Raised",
  "Category": "Category",
  "FAQ title": "FAQ title",
  "FAQ description": "FAQ description",
  "You must enter FAQ title and description":
      "You must enter FAQ title and description",
  "Related campaigns": "Related campaigns",
  "Edit": "Edit",
  "Delete": "Delete",
  "People who donated": "People who donated",
  "Image": "Image",
  "Choose image": "Choose image",
  "Featured campaign": "Featured campaign",
  "Featured campaigns": "Featured campaigns",
  "Edit campaign": "Edit campaign",
  "Title": "Title",
  "Description": "Description",
  "Campaign description": "Campaign description",
  "Amount": "Amount",
  "Please enter amount goal": "Please enter amount goal",
  "End date": "End date",
  "Are you sure?": "Are you sure?",
  "Cancel": "Cancel",
  "My campaigns": "My campaigns",
  "You do not have any campaign": "You do not have any campaign",
  "Recent campaign": "Recent campaign",
  "Recent campaigns": "Recent campaigns",
  "No campaign found": "No campaign found",
  "Following": "Following",
  "Follow": "Follow",
  "Something went wrong": "Something went wrong",
  "Write a Comment": "Write a Comment",
  "Donate": "Donate",
  "Create campaign": "Create campaign",
  "Please enter campaign title": "Please enter campaign title",
  "Create": "Create",
  "You must enter a description": "You must enter a description",
  "You must enter a valid amount": "You must enter a valid amount",
  "Campaigns": "Campaigns",
  "Following user campaigns": "Following user campaigns",
  "No user followed": "No user followed",
  "Write a comment": "Write a comment",
  "Comment": "Comment",
  "Events booking": "Events booking",
  "Total donations": "Total donations",
  "Total campaign": "Total campaign",
  "Total reward pts": "Total reward pts",
  "Dashboard": "Dashboard",
  "Recent donations": "Recent donations",
  "Donations ID": "Donations ID",
  "Payment Gateway": "Payment Gateway",
  "Date": "Date",
  "No donation record found": "No donation record found",
  "All donations": "All donations",
  "No": "No",
  "Yes": "Yes",
  "Events": "Events",
  "Book seat": "Book seat",
  "No events found": "No events found",
  "Please enter your Email": "Please enter your Email",
  "Quantity": "Quantity",
  "Please enter how many tickets you want to buy":
      "Please enter how many tickets you want to buy",
  "Choose payment method": "Choose payment method",
  "Confirm": "Confirm",
  "Please select a payment method": "Please select a payment method",
  "Event venue": "Event venue",
  "Name": "Name",
  "Locaiton": "Locaiton",
  "Available seat": "Available seat",
  "Reserve your seat": "Reserve your seat",
  "Events Bookings": "Events Bookings",
  "Ticket price": "Ticket price",
  "Payment status": "Payment status",
  "No event found": "No event found",
  "Home": "Home",
  "Menu": "Menu",
  "Profile": "Profile",
  "Categories": "Categories",
  "No category found": "No category found",
  "Quick Donations": "Quick Donations",
  "See all": "See all",
  "All categories": "All categories",
  "Hello": "Hello",
  "Could not load user profile info": "Could not load user profile info",
  "Press again to exit": "Press again to exit",
  "You do not have permission to create campaign":
      "You do not have permission to create campaign",
  "Events Booking": "Events Booking",
  "All Donations": "All Donations",
  "Following User Campaigns": "Following User Campaigns",
  "All Support Ticket": "All Support Ticket",
  "Reward Points": "Reward Points",
  "Your Donation Details": "Your Donation Details",
  "Total": "Total",
  "Payment": "Payment",
  "Minimum donation amount": "Minimum donation amount",
  "Pick an amount": "Pick an amount",
  "Or enter an amount": "Or enter an amount",
  "Amount must be greater than zero": "Amount must be greater than zero",
  "Donate anonymously": "Donate anonymously",
  "I agree with terms and conditions": "I agree with terms and conditions",
  "Pay & Confirm": "Pay & Confirm",
  "Please enter or select an amount": "Please enter or select an amount",
  "Amount must be greater than": "Amount must be greater than",
  "You must agree with the terms and conditions":
      "You must agree with the terms and conditions",
  "Booking Successfull": "Booking Successfull",
  "Your booking for the event is successful, ID is":
      "Your booking for the event is successful, ID is",
  "See booked events": "See booked events",
  "Donated successfully!": "Donated successfully!",
  "Your donation has been successful!, Order ID is":
      "Your donation has been successful!, Order ID is",
  "See all donations": "See all donations",
  "Logout": "Logout",
  "Change Password": "Change Password",
  "Enter current password": "Enter current password",
  "Enter your current password": "Enter your current password",
  "Retype new password": "Retype new password",
  "Edit profile": "Edit profile",
  "Please wait while the profile is updating":
      "Please wait while the profile is updating",
  "Phone": "Phone",
  "Please enter your phone": "Please enter your phone",
  "Enter your phone": "Enter your phone",
  "State": "State",
  "Please enter your state": "Please enter your state",
  "Enter your state": "Enter your state",
  "Zip": "Zip",
  "Please enter your zip": "Please enter your zip",
  "Enter your zip": "Enter your zip",
  "Address": "Address",
  "Please enter your address": "Please enter your address",
  "Enter your address": "Enter your address",
  "Save": "Save",
  "Address field is required": "Address field is required",
  "Phone field is required": "Phone field is required",
  "Updating profile...It may take few seconds":
      "Updating profile...It may take few seconds",
  "Zip Code": "Zip Code",
  "Country": "Country",
  "Log Out": "Log Out",
  "Redeemable Amount": "Redeemable Amount",
  "Withdraw Amount": "Withdraw Amount",
  "Please enter your amount": "Please enter your amount",
  "Enter your amount": "Enter your amount",
  "Gateway": "Gateway",
  "Payment Account Details": "Payment Account Details",
  "Please enter details": "Please enter details",
  "Details": "Details",
  "Additional Comment": "Additional Comment",
  "Submit": "Submit",
  "Reward points": "Reward points",
  "No data found": "No data found",
  "Redeem": "Redeem",
  "ID": "ID",
  "Points": "Points",
  "Create ticket": "Create ticket",
  "Priority": "Priority",
  "Please enter ticket title": "Please enter ticket title",
  "Ticket title": "Ticket title",
  "Support tickets": "Support tickets",
  "No ticket": "No ticket",
  "Attachment": "Attachment",
  "Payment Failed": "Payment Failed",
  "Back to Home": "Back to Home",
  "Your payment process will be terminated.":
      "Your payment process will be terminated.",
  "Donation payment failed!": "Donation payment failed!",
  "Write message": "Write message",
  "Edit Profile": "Edit Profile",
  "Time expired": "Time expired",
  "FAQ": "FAQ",
  "Updates": "Updates",
  "Comments": "Comments",
  "Days": "Days",
  "Hours": "Hours",
  "Minutes": "Minutes",
  "Seconds": "Seconds",
  "Location": "Location",
  "Tip": "Tip",
  "Urgent": "Urgent",
  "High": "High",
  "Medium": "Medium",
  "Low": "Low",
  "Please explain your problem": "Please explain your problem",
  "Please write a message first": "Please write a message first",
  "Make sure you repeated new password correctly":
      "Make sure you repeated new password correctly",
  "Please turn on your internet connection":
      "Please turn on your internet connection",
  "Password changed successfully": "Password changed successfully",
  "Your entered the otp correctly but something went wrong. Please try again later":
      "Your entered the otp correctly but something went wrong. Please try again later",
  "Otp not entered": "Otp not entered",
  "Didn't get any user info after google sign in. visit google sign in service file":
      "Didn't get any user info after google sign in. visit google sign in service file",
  "Password updated successfully": "Password updated successfully",
  "Registration successful": "Registration successful",
  "Otp send failed": "Otp send failed",
  "Payment failed": "Payment failed",
  "Ok": "Ok",
  "Please check your internet connection":
      "Please check your internet connection",
  "Ticket created successfully": "Ticket created successfully",
  "Only zip file is supported": "Only zip file is supported",
  "Check your internet connection": "Check your internet connection",
  "Payment successful": "Payment successful",
  "Failed to make payment status successfull":
      "Failed to make payment status successfull",
  "Check your internet connection and try again":
      "Check your internet connection and try again",
  "Event booked successfully": "Event booked successfully",
  "Event canceled successfully": "Event canceled successfully",
  "Profile updated successfully": "Profile updated successfully",
  "Release to load more": "Release to load more",
  "Load Failed": "Load Failed",
  "No more Data": "No more Data",
  "Full Address": "Full Address",
  "Enter your full address": "Enter your full address",
  "Enter your country": "Enter your country",
  "Taxpayer No.": "Taxpayer No.",
  "Enter your taxpayer no.": "Enter your taxpayer no.",
  "Citizen card/Passport/Authorization": "Citizen card/Passport/Authorization",
  "Enter your Citizen card/Passport/Authorization":
      "Enter your Citizen card/Passport/Authorization",
  "Birth date": "Birth date",
  "Enter your birth date": "Enter your birth date",
  "NIPC": "NIPC",
  "Enter NIPC": "Enter NIPC",
  "Enter CAE": "Enter CAE",
  "CAE": "CAE",
  "Use this reference to pay": "Use this reference to pay",
  "You must select a category": "You must select a category",
  "You must select an image": "You must select an image",
  "Campaign created successfully": "Campaign created successfully",
  "You don\"t have any campaign": "You don\"t have any campaign",
  "Chat": "Chat",
  "open": "open",
  "close": "close",
  "Select Campaign": "Select Campaign",
  "Campaign updated successfully": "Campaign updated successfully",
  "Donated successfully": "Donated successfully",
  "Select Category": "Select Category",
  "Select State": "Select State",
  "Select Country": "Select Country",
  "Invalid Email or Password": "Invalid Email or Password",
  "Otp is null": "Otp is null",
  "complete": "complete",
  "Otp didn't match": "Otp didn't match",
  "pending": "pending",
  "Delete Account": "Delete Account",
  "Account Delete": "Account Delete",
  "Account deleted successfully": "Account deleted successfully",
  "Account delete failed": "Account delete failed",
  "Enter your reason...": "Enter your reason...",
  "Password must be at least 6 character":
      "Password must be at least 6 character",
  "Your account is deactivated": "Your account is deactivated",
  "Password should be at least 8 characters long":
      "Password should be at least 8 characters long",
  "Password should contain at least 1 uppercase letter":
      "Password should contain at least 1 uppercase letter",
  "Password should contain at least 1 lowercase letter":
      "Password should contain at least 1 lowercase letter",
  "Password should contain at least 1 digit":
      "Password should contain at least 1 digit",
  "Password should contain at least 1 special character":
      "Password should contain at least 1 special character",
  "Sign Up": "Sign Up",
  "Sign In": "Sign In",
  "Enter a valid phone": "Enter a valid phone",
  "Sign in to comment": "Sign in to comment",
  "Apple id revoked successfully": "Apple id revoked successfully",
  "Apple id revoke failed": "Apple id revoke failed",
  "Hello! 👋": "Hello! 👋",
  "Welcome to Fundorex": "Welcome to Fundorex",
  "I agree to": "I agree to",
  "the terms & condition": "the terms & condition",
  "and": "and",
  "privacy policy": "privacy policy",
  "below": "below",
  "Terms & Condition": "Terms & Condition",
  "Privacy policy": "Privacy policy",
  "Get Reward by donating above": "Get Reward by donating above",
  "You'll have to login/register to edit or see your profile info.":
      "You'll have to login/register to edit or see your profile info.",
  "Login/Register": "Login/Register",
  "Welcome back! Login": "Welcome back! Login",
  "View Details": "View Details",
  "below": "below",
};
